/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PxOaUbYjSdE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function LandingPage() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header
        className="bg-gray-950 text-gray-50 px-4 md:px-6 py-4 flex items-center justify-between">
        <nav className="flex items-center gap-6">
          <Link className="font-bold text-lg" href="#">
            SARF
          </Link>
          <Link className="text-sm hover:underline scroll-smooth" href="#">
            About
          </Link>
          <Link className="text-sm hover:underline scroll-smooth" href="#">
            Contact
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <Link className="text-sm font-medium hover:underline" href="#">
            Login
          </Link>
          <Link
            className="inline-flex h-8 items-center justify-center rounded-md bg-gray-50 px-4 text-sm font-medium text-gray-950 transition-colors hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-950 focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
            href="#">
            Sign Up
          </Link>
        </div>
      </header>
      <main className="flex-1 snap-y snap-mandatory overflow-y-scroll">
        <section className="flex items-center justify-center bg-gray-950 text-gray-50 px-4 md:px-6 h-[80dvh] snap-start">
          <div className="space-y-8 text-center max-w-[700xpx]">
            {/* <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Automated + Interest Free Loans</h1> */}
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Financial Wellness For All</h1>
            {/* <div> <h2 className="md:text-xl/relaxed">Financial Wellness For All</h2></div> */}
            <h4 className="text-2xl font-bold tracking-tighter">Automated + Interest Free Loans</h4>
          </div>
        </section>
        <section
          className="flex items-center justify-center bg-gray-950 text-gray-50 px-4 md:px-6 py-12 h-[60dvh] snap-start scroll-mt-16"
          id="about">
          <div className="container">
            {/* <h2 className="text-2xl font-bold mb-8">About</h2> */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
              <div className="space-y-4">
                <RocketIcon className="h-12 w-12 mx-auto" />
                <h3 className="text-2xl font-bold">Innovative Solutions</h3>
                <p className="text-gray-400 md:text-xl/relaxed">
                  Our cutting-edge platform and expert team are dedicated to providing innovative solutions to help your
                  business thrive.
                </p>
              </div>
              <div className="space-y-4">
                <BoltIcon className="h-12 w-12 mx-auto" />
                <h3 className="text-2xl font-bold">Unparalleled Performance</h3>
                <p className="text-gray-400 md:text-xl/relaxed">
                  Experience lightning-fast speed and uncompromising reliability with our platform, designed to deliver
                  exceptional results.
                </p>
              </div>
              <div className="space-y-4">
                <UsersIcon className="h-12 w-12 mx-auto" />
                <h3 className="text-2xl font-bold">Dedicated Support</h3>
                <p className="text-gray-400 md:text-xl/relaxed">
                  Our expert team is here to provide personalized support and guidance, ensuring your success every step
                  of the way.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          className="flex items-center justify-center bg-gray-950 text-gray-50 px-4 md:px-6 py-12 h-[50dvh] snap-start scroll-mt-16"
          id="contact">
          <div className="space-y-8 text-center max-w-[600px]">
            <h2 className="text-2xl font-bold">Contact</h2>
            <p className="text-gray-400 md:text-xl/relaxed">
              Get in touch with us to learn more about our services and how we can help you succeed online.
            </p>
            <div className="flex justify-center gap-4">
              <Link
                className="inline-flex items-center gap-2 text-sm font-medium hover:underline"
                href="#">
                <MailIcon className="h-5 w-5" />
                info@sarf.com
              </Link>
              <Link
                className="inline-flex items-center gap-2 text-sm font-medium hover:underline"
                href="#">
                <PhoneIcon className="h-5 w-5" />
                +1 (234) 567-890
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function BoltIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}


function RocketIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path
        d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
